from enum import Enum

# Enum para as varas federais
class VarasFederais(Enum): 
    VARA_FOZ_3 = "3ª Vara Federal de Foz do Iguaçu"
    VARA_FOZ_5 = "5ª Vara Federal de Foz do Iguaçu"
    VARA_CASCAVEL_4 = "4ª Vara Federal de Cascavel"
    VARA_LONDRINA_5 = "5ª Vara Federal de Londrina"
    VARA_GUAIRA = "1ª Vara Federal de Guaíra"
    VARA_MARINGA_3 = "3ª Vara Federal de Maringá"
    VARA_MARINGA_6 = "6ª Vara Federal de Maringá" #Somente previdênciarios
    VARA_CURITIBA_13 = "13ª Vara Federal de Curitiba"
    VARA_CURITIBA_14 = "14ª Vara Federal de Curitiba"
    VARA_CURITIBA_23 = "23ª Vara Federal de Curitiba"
    VARA_UMUARAMA_1 = "1ª Vara Federal de Umuarama"
    VARA_PONTA_GROSSA_1 = "1ª Vara Federal de Ponta Grossa"

    VARA_APUCARANA = "1ª Vara Federal de Apucarana"
    PERICIA_APUCARANA = "Perícias - Apucarana"
    UAA_APUCARANA_1 = "1ª UAA em Apucarana"
    UAA_APUCARANA_2 = "2ª UAA em Apucarana"
    UAA_APUCARANA_3 = "3ª UAA em Apucarana"

    PERICIA_ARAPONGAS = "Perícias - Arapongas"
    UAA_ARAPONGAS_1 = "1ª UAA em Arapongas"
    UAA_ARAPONGAS_2 = "2ª UAA em Arapongas"
    UAA_ARAPONGAS_3 = "3ª UAA em Arapongas"
    UAA_ARAPONGAS_4 = "4ª UAA em Arapongas"
    UAA_ARAPONGAS_5 = "5ª UAA em Arapongas"
    UAA_ARAPONGAS_6 = "6ª UAA em Arapongas"
    UAA_ARAPONGAS_7 = "7ª UAA em Arapongas"

    PERICIA_ASTORGA_LONDRINA = "Perícias - Astorga - Londrina"
    UAA_ASTORGA_1 = "1ª UAA em Astorga"
    UAA_ASTORGA_2 = "2ª UAA em Astorga"
    UAA_ASTORGA_3 = "3ª UAA em Astorga"
    UAA_ASTORGA_4 = "4ª UAA em Astorga"
    UAA_ASTORGA_5 = "5ª UAA em Astorga"
    UAA_ASTORGA_6 = "6ª UAA em Astorga"
    UAA_ASTORGA_7 = "7ª UAA em Astorga"
    UAA_ASTORGA_13 = "13ª UAA em Astorga"

    PERICIA_ASTORGA_MARINGA = "Perícias - Astorga - Maringá"
    UAA_ASTORGA_8 = "8ª UAA em Astorga"
    UAA_ASTORGA_9 = "9ª UAA em Astorga"
    UAA_ASTORGA_10 = "10ª UAA em Astorga"
    UAA_ASTORGA_11 = "11ª UAA em Astorga"
    UAA_ASTORGA_12 = "12ª UAA em Astorga"
    UAA_ASTORGA_14 = "14ª UAA em Astorga"

    VARA_CAMPO_MOURAO_1 = "1ª Vara Federal de Campo Mourão"
    VARA_CAMPO_MOURAO_2 = "2ª Vara Federal de Campo Mourão"
    CEJUSCON_CAMPO_MOURAO = "CEJUSCON - Campo Mourão"
    PERICIA_CAMPO_MOURAO = "Perícias - Campo Mourão"

    VARA_CASCAVEL_1 = "1ª Vara Federal de Cascavel"
    VARA_CASCAVEL_2 = "2ª Vara Federal de Cascavel"
    VARA_CASCAVEL_3 = "3ª Vara Federal de Cascavel"
    CEJUSCON_CASCAVEL = "CEJUSCON - Cascavel"
    PERICIA_CASCAVEL = "Perícias - Cascavel"

    VARA_CURITIBA_1 = "1ª Vara Federal de Curitiba"
    VARA_CURITIBA_2 = "2ª Vara Federal de Curitiba"
    VARA_CURITIBA_3 = "3ª Vara Federal de Curitiba"
    VARA_CURITIBA_4 = "4ª Vara Federal de Curitiba"
    VARA_CURITIBA_5 = "5ª Vara Federal de Curitiba"
    VARA_CURITIBA_05A = "05A VF de Curitiba (Antiga)"
    VARA_CURITIBA_6 = "6ª Vara Federal de Curitiba"
    VARA_CURITIBA_06A = "06A VF de Curitiba (Antiga)"
    VARA_CURITIBA_7 = "7ª Vara Federal de Curitiba"
    VARA_CURITIBA_8 = "8ª Vara Federal de Curitiba"
    VARA_CURITIBA_9 = "9ª Vara Federal de Curitiba"
    VARA_CURITIBA_10 = "10ª Vara Federal de Curitiba"
    VARA_CURITIBA_11 = "11ª Vara Federal de Curitiba"
    VARA_CURITIBA_12 = "12ª Vara Federal de Curitiba"
    VARA_CURITIBA_15 = "15ª Vara Federal de Curitiba"
    VARA_CURITIBA_16 = "16ª Vara Federal de Curitiba"
    VARA_CURITIBA_17 = "17ª Vara Federal de Curitiba"
    VARA_CURITIBA_18 = "18ª Vara Federal de Curitiba"
    VARA_CURITIBA_19 = "19ª Vara Federal de Curitiba"
    VARA_CURITIBA_20 = "20ª Vara Federal de Curitiba"
    VARA_CURITIBA_21 = "21ª Vara Federal de Curitiba"
    VARA_CURITIBA_22 = "22ª Vara Federal de Curitiba"
    JUSTICA_RESTAURATIVA_CURITIBA = "Justiça Restaurativa - Curitiba"
    EXECUCAO_PENAL_CATANDUVAS = "Execução Penal de Catanduvas"
    DIVISAO_CONCILIACOES = "Divisão de Conciliações"
    NUCLEO_JUSTICA_1 = "1° Núcleo de Justiça 4.0 - PR"
    NUCLEO_JUSTICA_3 = "3° Núcleo de Justiça 4.0 - PR"
    PERICIA_CURITIBA = "Perícias - Curitiba"
    UAA_CURITIBA = "1ª Unidade de Apoio de Curitiba"
    VARA_PORTO_ALEGRE = "26ª Vara Federal de Porto Alegre"

    VARA_FOZ_1 = "1ª Vara Federal de Foz do Iguaçu"
    VARA_FOZ_2 = "2ª Vara Federal de Foz do Iguaçu"
    VARA_FOZ_4 = "4ª Vara Federal de Foz do Iguaçu"
    VARA_FOZ_6 = "6ª Vara Federal de Foz do Iguaçu"
    CEJUSCON_FOZ = "CEJUSCON - Foz do Iguaçu"
    PERICIA_FOZ = "Perícias - Foz do Iguaçu"

    VARA_FRANCISCO_BELTRAO_1 = "1ª Vara Federal de Francisco Beltrão"
    VARA_FRANCISCO_BELTRAO_2 = "2ª Vara Federal de Francisco Beltrão"
    CEJUSCON_FRANCISCO_BELTRAO = "CEJUSCON - Francisco Beltrão"
    PERICIA_FRANCISCO_BELTRAO = "Perícias - Francisco Beltrão"

    PERICIA_GUAIRA = "Perícias - Guaíra"

    VARA_GUARAPUAVA_1 = "1ª Vara Federal de Guarapuava"
    VARA_GUARAPUAVA_2 = "2ª Vara Federal de Guarapuava"
    CEJUSCON_GUARAPUAVA = "CEJUSCON - Guarapuava"
    PERICIA_GUARAPUAVA = "Perícias - Guarapuava"

    PERICIA_IBAITI_JACAREZINHO = "Perícias - Ibaiti - Jacarezinho"
    UAA_IBAITI_1 = "1ª UAA em Ibaiti"
    UAA_IBAITI_15 = "15ª UAA de Ibaiti"

    PERICIA_IBAITI_LONDRINA = "Perícias - Ibaiti - Londrina"
    UAA_IBAITI_2 = "2ª UAA em Ibaiti"
    UAA_IBAITI_3 = "3ª UAA em Ibaiti"
    UAA_IBAITI_4 = "4ª UAA em Ibaiti"
    UAA_IBAITI_5 = "5ª UAA em Ibaiti"
    UAA_IBAITI_6 = "6ª UAA em Ibaiti"
    UAA_IBAITI_7 = "7ª UAA em Ibaiti"
    UAA_IBAITI_8 = "8ª UAA em Ibaiti"
    UAA_IBAITI_9 = "9ª UAA em Ibaiti"
    UAA_IBAITI_10 = "10ª UAA em Ibaiti"
    UAA_IBAITI_11 = "11ª UAA em Ibaiti"
    UAA_IBAITI_12 = "12ª UAA em Ibaiti"
    UAA_IBAITI_13 = "13ª UAA em Ibaiti"

    PERICIA_IBAITI_TELEMACO = "Perícias - Ibaiti - Telêmaco Borba"
    UAA_IBAITI_14 = "14ª UAA de Ibaiti"

    PERICIA_IVAIPORA = "Perícias - Ivaiporã"
    UAA_IVAIPORA_1 = "1ª UAA em Ivaiporã"
    UAA_IVAIPORA_2 = "2ª UAA em Ivaiporã"
    UAA_IVAIPORA_3 = "3ª UAA em Ivaiporã"

    VARA_JACAREZINHO = "1ª Vara Federal de Jacarezinho"
    PERICIA_JACAREZINHO = "Perícias - Jacarezinho"
    UAA_JACAREZINHO_1 = "1ª Unidade de Apoio Itinerante em Jacarezinho"
    UAA_JACAREZINHO_2 = "2ª Unidade de Apoio Itinerante em Jacarezinho"
    UAA_JACAREZINHO_3 = "3ª Unidade de Apoio Itinerante em Jacarezinho"

    VARA_LONDRINA_1 = "1ª Vara Federal de Londrina"
    VARA_LONDRINA_2 = "2ª Vara Federal de Londrina"
    VARA_LONDRINA_3 = "3ª Vara Federal de Londrina"
    VARA_LONDRINA_4 = "4ª Vara Federal de Londrina"
    VARA_LONDRINA_6 = "6ª Vara Federal de Londrina"
    VARA_LONDRINA_7 = "7ª Vara Federal de Londrina"
    VARA_LONDRINA_8 = "8ª Vara Federal de Londrina"
    CEJUSCON_LONDRINA = "CEJUSCON - Londrina"
    PERICIA_LONDRINA = "Perícias - Londrina"

    VARA_MARINGA_1 = "1ª Vara Federal de Maringá"
    VARA_MARINGA_2 = "2ª Vara Federal de Maringá"
    VARA_MARINGA_4 = "4ª Vara Federal de Maringá"
    VARA_MARINGA_5 = "5ª Vara Federal de Maringá"
    CEJUSCON_MARINGA = "CEJUSCON - Maringá"
    PERICIA_MARINGA = "Perícias - Maringá"

    VARA_PARANAGUA = "1ª Vara Federal de Paranaguá"
    PERICIA_PARANAGUA = "Perícias - Paranaguá"

    VARA_PARANAVAI = "1ª Vara Federal de Paranavaí"
    PERICIA_PARANAVAI = "Perícias - Paranavaí"

    VARA_PATO_BRANCO = "1ª Vara Federal de Pato Branco"
    PERICIA_PATO_BRANCO = "Perícias - Pato Branco"

    VARA_PITANGA_1 = "1ª Vara Federal de Pitanga"
    PERICIA_PITANGA = "Perícias - Pitanga"
    UAA_PITANGA_4 = "4ª UAA em Pitanga"
    UAA_PITANGA_3 = "3ª UAA em Pitanga"
    UAA_PITANGA_1 = "1ª UAA em Pitanga"
    UAA_PITANGA_2 = "2ª UAA em Pitanga"

    VARA_PONTA_GROSSA_2 = "2ª Vara Federal de Ponta Grossa"
    VARA_PONTA_GROSSA_3 = "3ª Vara Federal de Ponta Grossa"
    VARA_PONTA_GROSSA_4 = "4ª Vara Federal de Ponta Grossa"
    CEJUSCON_PONTA_GROSSA = "CEJUSCON - Ponta Grossa"
    PERICIA_PONTA_GROSSA = "Perícias - Ponta Grossa"

    VARA_TELEMACO_BORBA = "1ª Vara Federal de Telêmaco Borba"
    PERICIA_TELEMACO_BORBA = "Perícias - Telêmaco Borba"

    VARA_TOLEDO = "1ª Vara Federal de Toledo"
    PERICIA_TOLEDO = "Perícias - Toledo"

    VARA_UMUARAMA_2 = "2ª Vara Federal de Umuarama"
    VARA_UMUARAMA_3 = "3ª Vara Federal de Umuarama"
    CEJUSCON_UMUARAMA = "CEJUSCON - Umuarama"
    PERICIA_UMUARAMA = "Perícias - Umuarama"

    VARA_UNIAO_VITORIA = "1ª Vara Federal de União da Vitória"
    PERICIA_UNIAO_VITORIA = "Perícias - União da Vitória"

    PERICIA_WENCESLAU_BRAZ = "Perícias - Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_1 = "1ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_2 = "2ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_3 = "3ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_4 = "4ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_5 = "5ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_7 = "7ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_8 = "8ª UAA em Wenceslau Braz"
    UAA_WENCESLAU_BRAZ_6 = "6ª UAA em Wenceslau Braz"